# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ad5fd63ed03a0027588205f64d32722939737d93c3fa9dcae3507fa6a6721e85cb1a1d708da385a8cacd0cf461ce565920a8bee491438e139bb88a9d3d12172

test:
  secret_key_base: b95e4e2252b6e1fd360315a7463f48fa917fb5f2975cc51bc20d9bab149989337e40300227f844c54dfdb98fd51d5859b055ffe005d26a7cf09de1fbe9b0fbc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
